[package]
name = "tofu"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
argh = "0.1"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
tokio = { version = "1.8", features = ["full"] }
toml = "0.5"
warp = "0.3"
