on: [push, pull_request]

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
  check:
    name: Run Cargo Check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        with:
          command: check
  test:
    name: Run Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        with:
          command: test
  fmt:
    name: Run Rustfmt
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Run Clippy
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
